# Generated by Django 4.2.8 on 2023-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
